//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management_by_haris.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tbl_products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_products()
        {
            this.tbl_inventory = new HashSet<tbl_inventory>();
            this.tbl_orders = new HashSet<tbl_orders>();
        }
    
        public int pid { get; set; }
        [Required(ErrorMessage = "Name is required")]
        [RegularExpression("^[a-zA-Z]{1,100}", ErrorMessage = "Only 100 Alphabets.")]
        public string pname { get; set; }
        public string ptype { get; set; }
        [Required(ErrorMessage = "price is required")]
        [RegularExpression("^[0-9]{1,11}", ErrorMessage = "11 digits only.")]
        public Nullable<int> price { get; set; }
        [Required(ErrorMessage = "cost is required")]
        [RegularExpression("^[0-9]{1,11}", ErrorMessage = "11 digits only.")]
        public Nullable<int> cost { get; set; }
        [Required(ErrorMessage = "code is required")]
        [RegularExpression("^[a-zA-z0-9]{1,15}", ErrorMessage = "15 alphanumeric only.")]
        public string pcode { get; set; }
        [Required(ErrorMessage = "weight is required")]
        [RegularExpression("^[0-9]{1,11}", ErrorMessage = "11 digits only.")]
        public Nullable<int> pweight { get; set; }
        [Required(ErrorMessage = "price is required")]
        [RegularExpression("^[0-9a-zA-Z]{1,300}", ErrorMessage = "300 alphanumeric only.")]
        public string pdescription { get; set; }
        public string pimage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_inventory> tbl_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_orders> tbl_orders { get; set; }
    }
}
