//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management_by_haris.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tbl_inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_inventory()
        {
            this.tbl_cart = new HashSet<tbl_cart>();
            this.tbl_orders = new HashSet<tbl_orders>();
        }
    
        public int id { get; set; }
        public Nullable<int> pid { get; set; }
        [Required(ErrorMessage = "Quantity is required")]
        [RegularExpression("^[0-9]{1,11}", ErrorMessage = "11 digits only.")]
        public Nullable<int> quantity { get; set; }
        [Required(ErrorMessage = "date is required")]
        public Nullable<System.DateTime> idate { get; set; }
    
        public virtual tbl_products tbl_products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cart> tbl_cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_orders> tbl_orders { get; set; }
    }
}
